name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        julia-arch: [x64]
        julia-version: ["1.7"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      - name: Set up Julia caches
        uses: julia-actions/cache@v1
        with:
          cache-name: ${{ matrix.julia-arch }}-${{ matrix.julia-version }}
          cache-registries: "true"

      - name: Build package
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest

      - name: Process coverage data
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src

      - name: Upload code coverage data to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: 7c23e583-ed11-43ef-8fe6-54307b67830c
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
