name: CI

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        julia-arch: [x64]
        julia-version: ["1.6", "1.7"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      - name: Set up Julia caches
        uses: julia-actions/cache@v1
        with:
          cache-name: ${{ matrix.julia-arch }}-${{ matrix.julia-version }}

      - name: Build package
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest
