name: codecov

on:
  pull_request_target:
    types:
      - closed
    branches:
      - dev

jobs:
  if_merged:
    if: github.event.pull_request_target.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Process coverage data
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src

      - name: Upload code coverage data to codecov.io
        uses: codecov/codecov-action@v2
        with:
          # token: not required for public repos
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
