name: pull-request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [x64]
        julia-version: ["1.6", "1.7"]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Julia environment
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}

      - name: Set up Julia caches
        uses: julia-actions/cache@v1
        with:
          cache-name: ${{ runner.arch }}-${{ matrix.julia-version }}

#      - name: Set up cache
#        uses: actions/cache@v2
#        env:
#          cache-name: artifacts+packages
#        with:
#          path: |
#              ~/.julia/artifacts
#              ~/.julia/packages
#
#          key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.julia-version }}-cache-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
#
#          restore-keys: |
#            ${{ runner.os }}-${{ runner.arch }}-${{ matrix.julia-version }}-cache-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
#            ${{ runner.os }}-${{ runner.arch }}-${{ matrix.julia-version }}-cache-${{ env.cache-name }}-
##            ${{ runner.os }}-${{ runner.arch }}-${{ matrix.julia-version }}-cache-
##            ${{ runner.os }}-${{ runner.arch }}-${{ matrix.julia-version }}-
##            ${{ runner.os }}-${{ runner.arch }}-
##            ${{ runner.os }}-

      - name: Build package
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest
