name: tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]
        julia-version: ["1.7"]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}

      - name: Set up Julia caches
        uses: julia-actions/cache@v1
        with:
          cache-registries: "true"
          cache-name: ${{ matrix.arch }}-${{ matrix.julia-version }}

#      - name: Set up cache
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-artifacts+packages
#        with:
#          path: |
#              ~/.julia/artifacts
#              ~/.julia/packages
#        with:
#          path: ~/.julia/artifacts
#          key: ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.julia-version }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
#          restore-keys: |
#            ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.julia-version }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
#            ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.julia-version }}-test-${{ env.cache-name }}-
#            ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.julia-version }}-test-
#            ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.julia-version }}-
#            ${{ runner.os }}-${{ matrix.arch }}-
#            ${{ runner.os }}-

      - name: Build package
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest

      - name: Process coverage data
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src

      - name: Upload code coverage data to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: 7c23e583-ed11-43ef-8fe6-54307b67830c
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
